### ISSUE TITLE
No ability to link specific lines within texts

### ISSUE THREAD

**Issue by snshn** [Lyrics/lyrics-website-generator#60]
Might be a cool feature, e.g.: https://lyrics.github.io/db/A/Artist/Album/Recording#L12

**Comment by defanor** [comment]
That's potentially useful for any (hyper)textual document, so document viewers (and web browsers in particular) may be more appropriate to implement that in, rather than every document. There is [RFC 5147](https://tools.ietf.org/html/rfc5147) for text/plain (lines, characters, their ranges), although it's not supported by major web browsers still.

Could still do it for the sake of practicality, but not sure if it's useful enough.

**Comment by snshn** [comment]
I guess using github.com for that is enough, not like every day you want to link to a particular line in a song.
